spring.jpa.open-in-view: false

spring:
  profiles:
    active: local
    include:
      - momsitter
  mvc:
    contentnegotiation:
      favor-parameter: true
      favor-path-extension: true
      media-types:
        xls: application/vnd.ms-excel

server:
  port: 9096
  servlet:
    session:
      timeout: 10800

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  endpoint:
    health:
      enabled: true
      show-details: never
    prometheus:
      cache:
        time-to-live: 10s
  metrics:
    export:
      prometheus:
        enabled: true

notification:
  corporation:
    name: "맘시터서비스 API"
